// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjImmmcO9hec-scmokx6vLKch6bNnY6c',
    appId: '1:82013093789:web:403101aa0de21b19103974',
    messagingSenderId: '82013093789',
    projectId: 'hele-903b7',
    authDomain: 'hele-903b7.firebaseapp.com',
    storageBucket: 'hele-903b7.firebasestorage.app',
    measurementId: 'G-81VNXG3F31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhM_-_JVcnemESMQxDeuZHat1JHN8J7DA',
    appId: '1:82013093789:android:ec4e65308a2d0ebe103974',
    messagingSenderId: '82013093789',
    projectId: 'hele-903b7',
    storageBucket: 'hele-903b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8XgyV7voJ7DO1vJHadFE8WgSSQSbEao',
    appId: '1:82013093789:ios:f382187c5e9da8c5103974',
    messagingSenderId: '82013093789',
    projectId: 'hele-903b7',
    storageBucket: 'hele-903b7.firebasestorage.app',
    iosBundleId: 'com.example.redchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8XgyV7voJ7DO1vJHadFE8WgSSQSbEao',
    appId: '1:82013093789:ios:f382187c5e9da8c5103974',
    messagingSenderId: '82013093789',
    projectId: 'hele-903b7',
    storageBucket: 'hele-903b7.firebasestorage.app',
    iosBundleId: 'com.example.redchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPjImmmcO9hec-scmokx6vLKch6bNnY6c',
    appId: '1:82013093789:web:0fa6019e75ff17ee103974',
    messagingSenderId: '82013093789',
    projectId: 'hele-903b7',
    authDomain: 'hele-903b7.firebaseapp.com',
    storageBucket: 'hele-903b7.firebasestorage.app',
    measurementId: 'G-2YQLZRWLWD',
  );
}
